In [1]:
import pandas as pd
import numpy as np

orders = pd.DataFrame({
    'OrderID': [101,102,103,104,105,106,107,108,109,110],
    'Customer': ['Aman','Riya','Kabir','Aman','Sneha','Riya','Kabir','Meera','Aman','Sneha'],
    'Category': ['Electronics','Fashion','Electronics','Groceries','Fashion',
                 'Electronics','Fashion','Groceries','Electronics','Fashion'],
    'Amount': [5000,2000,np.nan,1500,3000,7000,2500,1200,5000,3000],
    'City': ['Mumbai','Delhi','Mumbai','Pune','Delhi',
             'Mumbai','Pune','Mumbai','Delhi','Delhi'],
    'OrderDate': ['2025-01-10','2025-01-12','2025-01-15','2025-02-01',
                  '2025-02-10','2025-02-18','2025-03-01',
                  '2025-03-05','2025-03-20','2025-03-25']
})

customers = pd.DataFrame({
    'Customer': ['Aman','Riya','Kabir','Sneha','Meera'],
    'Age': [21,24,22,23,25],
    'Membership': ['Gold','Silver','Gold','Platinum','Silver']
})

In [6]:
# Task 1 — Basic Inspection

# Display:

# first 5 rows
# dataframe shape
# column names
# data types

display(orders.head(5))
display(orders.shape)
display(orders.columns)
display(orders.dtypes)

   OrderID Customer     Category  Amount    City   OrderDate
0      101     Aman  Electronics  5000.0  Mumbai  2025-01-10
1      102     Riya      Fashion  2000.0   Delhi  2025-01-12
2      103    Kabir  Electronics     NaN  Mumbai  2025-01-15
3      104     Aman    Groceries  1500.0    Pune  2025-02-01
4      105    Sneha      Fashion  3000.0   Delhi  2025-02-10

(10, 6)

Index(['OrderID', 'Customer', 'Category', 'Amount', 'City', 'OrderDate'], dtype='object')

OrderID        int64
Customer      object
Category      object
Amount       float64
City          object
OrderDate     object
dtype: object

In [7]:
display(orders.isnull())
orders.fillna(orders['Amount'].mean(), inplace = True)
display(orders.isnull())

   OrderID  Customer  Category  Amount   City  OrderDate
0    False     False     False   False  False      False
1    False     False     False   False  False      False
2    False     False     False    True  False      False
3    False     False     False   False  False      False
4    False     False     False   False  False      False
5    False     False     False   False  False      False
6    False     False     False   False  False      False
7    False     False     False   False  False      False
8    False     False     False   False  False      False
9    False     False     False   False  False      False

   OrderID  Customer  Category  Amount   City  OrderDate
0    False     False     False   False  False      False
1    False     False     False   False  False      False
2    False     False     False   False  False      False
3    False     False     False   False  False      False
4    False     False     False   False  False      False
5    False     False     False   False  False      False
6    False     False     False   False  False      False
7    False     False     False   False  False      False
8    False     False     False   False  False      False
9    False     False     False   False  False      False

In [13]:
orders.OrderDate = pd.to_datetime(orders.OrderDate)
display(orders.dtypes)

#give  month names in month column

orders['Month'] = orders.OrderDate.dt.month_name()
display(orders.head(5))

OrderID               int64
Customer             object
Category             object
Amount              float64
City                 object
OrderDate    datetime64[ns]
Month                 int32
dtype: object

   OrderID Customer     Category       Amount    City  OrderDate     Month
0      101     Aman  Electronics  5000.000000  Mumbai 2025-01-10   January
1      102     Riya      Fashion  2000.000000   Delhi 2025-01-12   January
2      103    Kabir  Electronics  3355.555556  Mumbai 2025-01-15   January
3      104     Aman    Groceries  1500.000000    Pune 2025-02-01  February
4      105    Sneha      Fashion  3000.000000   Delhi 2025-02-10  February

In [16]:
display(orders[orders['Amount'] > 3000])
display(orders[(orders['City'] == 'Mumbai') & (orders['Category'] == 'Electronics')])
display(orders[(orders['Category'] == 'Groceries') | (orders['Category'] == 'Fashion')])

   OrderID Customer     Category       Amount    City  OrderDate     Month
0      101     Aman  Electronics  5000.000000  Mumbai 2025-01-10   January
2      103    Kabir  Electronics  3355.555556  Mumbai 2025-01-15   January
5      106     Riya  Electronics  7000.000000  Mumbai 2025-02-18  February
8      109     Aman  Electronics  5000.000000   Delhi 2025-03-20     March

   OrderID Customer     Category       Amount    City  OrderDate     Month
0      101     Aman  Electronics  5000.000000  Mumbai 2025-01-10   January
2      103    Kabir  Electronics  3355.555556  Mumbai 2025-01-15   January
5      106     Riya  Electronics  7000.000000  Mumbai 2025-02-18  February

   OrderID Customer   Category  Amount    City  OrderDate     Month
1      102     Riya    Fashion  2000.0   Delhi 2025-01-12   January
3      104     Aman  Groceries  1500.0    Pune 2025-02-01  February
4      105    Sneha    Fashion  3000.0   Delhi 2025-02-10  February
6      107    Kabir    Fashion  2500.0    Pune 2025-03-01     March
7      108    Meera  Groceries  1200.0  Mumbai 2025-03-05     March
9      110    Sneha    Fashion  3000.0   Delhi 2025-03-25     March

In [17]:
orders['Customer'] = orders['Customer'].str.upper()
display(orders.head(5))

   OrderID Customer     Category       Amount    City  OrderDate     Month
0      101     AMAN  Electronics  5000.000000  Mumbai 2025-01-10   January
1      102     RIYA      Fashion  2000.000000   Delhi 2025-01-12   January
2      103    KABIR  Electronics  3355.555556  Mumbai 2025-01-15   January
3      104     AMAN    Groceries  1500.000000    Pune 2025-02-01  February
4      105    SNEHA      Fashion  3000.000000   Delhi 2025-02-10  February

In [18]:
orders.to_csv('orders.csv', index = False)